# Generated by Django 4.1.2 on 2023-02-26 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='CATEGORY')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Admin_Panel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('occupation', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('login', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=36)),
                ('content', models.TextField()),
                ('photo', models.ImageField(upload_to='soyphotos')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_panel.category')),
            ],
            options={
                'verbose_name': 'List of employees',
                'verbose_name_plural': 'List of employees',
                'ordering': ['title'],
            },
        ),
    ]
