# Generated by Django 4.1.2 on 2022-12-17 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='admin_panel',
            options={'ordering': ['title'], 'verbose_name': 'List of employees', 'verbose_name_plural': 'List of employees'},
        ),
        migrations.AddField(
            model_name='admin_panel',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_panel.category'),
        ),
    ]
